### PR TITLE
Support Python 3 and PyPy

### PR DESCRIPTION
**Pull request by jamadden**
- Remove zope.app.testing dep in favor of zope.app.wsgi
- 100% test coverage

### CODE REVIEW

**Comment by jamadden** [comment]
This one was very simple. The change from zope.app.tetsing to zope.app.wsgi was very limited in scope since there were no Browser tests. There was really very little code still in this package and the fixes there were the usual implemnts->implementer. 

The only thing that's slightly complicated is globalmodules.zcml where there were some moves to be accounted for from Py2 to Py3.

**Comment by jamadden** [comment]
Thanks for the review and approval. I'll go ahead and merge. Could we please get a PyPI release (or rights) when convenient? (Also for zope.app.rotterdam.)

**Comment by mgedmin** [comment]
You have rights now.

**Comment by jamadden** [comment]
Thanks! 4.0.0 of both is published.

**Pull request merged**
